- name: Correr el Robot
        env: 
          API_URL: ${{ secrets.API_URL }}
          API_KEY: ${{ secrets.API_KEY }}
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}  <-- ¡ESTA ES LA LÍNEA QUE FALTA!
        run: python robot.py
